# Generated by Django 4.0.6 on 2022-07-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('origin_url', models.URLField()),
                ('modified_url', models.CharField(blank=True, max_length=15, unique=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
